      - name: copy catalogue service
        ansible.builtin.template:
          src: catalogue.service.j2
          dest: /etc/systemd/system/catalogue.service
      
      - name: daemon reload the system service
        ansible.builtin.systemd_service:
          daemon_reload: true
      
      - name: enable and start the system service
        ansible.builtin.service:
          name: catalogue
          state: restarted
          enabled: yes